name: Create Shadow Release

on:
  workflow_dispatch:
  
jobs:
  duplicate:
    runs-on: ubuntu-latest

    steps:
      - name: Get Latest Release—Ñ
        id: get_latest_release
        run: |
          response=$(curl -s -H "Authorization: token ${{ secrets.PAT }}" https://api.github.com/repos/rzc0d3r/ESET-KeyGen/releases/latest)
          echo "$response" | jq -r '.assets_url'
